name: build-latex
on:
  push:
  pull_request:
jobs:
  pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: xu-cheng/latex-action@v4
        with:
          root_file: main.tex
          latexmk_use_xelatex: true
      - uses: actions/upload-artifact@v4
        with:
          name: paper-pdf
          path: main.pdf
